# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awardsite', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedsite',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awardsite.PostedSite'),
        ),
    ]
