# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsite', '0009_auto_20181014_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='cat_choice',
            field=models.CharField(choices=[('Design', 'Design'), ('Usability', 'Usability'), ('Content', 'Content')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
    ]
